//
//
//  공용 사용 스크립트
//
//

// 디버그 플래그
var isDebug = false;

/**
 * 디버그 플래그 true일 때만 다이얼로그를 띄우고
 * 디버그 플래그와 무관하게 콘솔에 로그
 * @param {*} msg 
 */
function alertAndLog(msg){
    if(isDebug){
        alert(msg);
    }
    console.log(msg);
}

// 타입 형식들
const DATELIST_ENTRY_TYPE_REL_FROM = 'rel_from';
const DATELIST_ENTRY_TYPE_REL_TO = 'rel_to';
const DATELIST_ENTRY_TYPE_REL_RANGE = 'rel_range';
const DATELIST_ENTRY_TYPE_ABS_FROM = 'abs_from';
const DATELIST_ENTRY_TYPE_ABS_TO = 'abs_to';
const DATELIST_ENTRY_TYPE_ABS_RANGE = 'abs_range';
const DATELIST_ENTRY_TYPES = [DATELIST_ENTRY_TYPE_REL_FROM, DATELIST_ENTRY_TYPE_REL_TO, DATELIST_ENTRY_TYPE_REL_RANGE, DATELIST_ENTRY_TYPE_ABS_FROM, DATELIST_ENTRY_TYPE_REL_TO, DATELIST_ENTRY_TYPE_ABS_RANGE];

// 타입 형식들 표시용
const LABEL_DATELIST_ENTRY_TYPES_REL_FROM = '해당 일수 부터';
const LABEL_DATELIST_ENTRY_TYPES_REL_TO = '해당 일수 까지';
const LABEL_DATELIST_ENTRY_TYPES_REL_RANGE = '해당 기간 (상대적)';
const LABEL_DATELIST_ENTRY_TYPES_ABS_FROM = '특정 날짜 부터';
const LABEL_DATELIST_ENTRY_TYPES_ABS_TO = '특정 날짜 까지';
const LABEL_DATELIST_ENTRY_TYPES_ABS_RANGE = '특정 기간 (절대적)';
const LABEL_DATELIST_ENTRY_TYPES = [LABEL_DATELIST_ENTRY_TYPES_REL_FROM, LABEL_DATELIST_ENTRY_TYPES_REL_TO, LABEL_DATELIST_ENTRY_TYPES_REL_RANGE, LABEL_DATELIST_ENTRY_TYPES_ABS_FROM, LABEL_DATELIST_ENTRY_TYPES_ABS_TO, LABEL_DATELIST_ENTRY_TYPES_ABS_RANGE];
